version: '3'
services:
  syncthing:
    image: personal-cms:latest
    container_name: personal-cms
    volumes:
      - ./content:/var/content
      - ./config.json:/etc/personal.cms.d/config.json
    ports:
      - 3000:3000
