version: '3'
services:
  syncthing:
    image: personal-cms:latest
    container_name: personal-cms
    volumes:
      - ./content:/var/content
      - ./personal.cms.d:/etc/personal.cms.d
    ports:
      - 3000:3000
